name: Create and publish a Docker image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_BASE_NAME: ${{ github.repository }}

jobs:
  # This job finds all subdirectories containing a Dockerfile and creates a JSON array of their names.
  # This output is then used by the `build-and-push-image` job to dynamically generate a build matrix.
  list-images:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.list-images.outputs.images }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: list images
        id: list-images
        run: |
          images=$(
            find * -maxdepth 1 -name Dockerfile -print0 \
            | xargs -0 -n1 dirname \
            | jq -R . \
            | jq -cs .
          )
          echo "images=${images}" >> $GITHUB_OUTPUT

  # This job builds and pushes a container image for each of the directories found by the `list-images` job.
  build-and-push-image:
    needs: [list-images]
    runs-on: ubuntu-latest
    # This strategy creates a parallel build for each image, which speeds up the overall workflow.
    strategy:
      matrix:
        image: ${{ fromJson(needs.list-images.outputs.images) }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      # These steps set up QEMU and Buildx to enable multi-platform builds.
      - name: Setup qemu
        uses: docker/setup-qemu-action@v3
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME }}/${{ matrix.image }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ matrix.image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME}}/${{ matrix.image }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
